### ISSUE TITLE
Any Instructions On How To Compile This?

### ISSUE THREAD

**Issue by sensui7** [guided-hacking/Age-of-Empires-II-2013#11]
I'm getting lots of errors whenever I'm compiling this on Microsoft Visual Studio Community 2019.

Does anyone know of instructions / requirements to compile this project?

**Comment by GH-Rake** [comment]
This was fixed in the last 2 commits, clone a new copy and try again.

If you're unfamiliar with D3D: https://guidedhacking.com/threads/how-to-get-started-with-directx-9-direct3d9-hooking.10402/

if you're unfamiliar with Imgui: https://guidedhacking.com/threads/guide-to-imgui-hooks-for-game-hack-menus.13993/
